apiVersion: apps/v1
kind: Deployment
metadata:
  name: riot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot-api
  template:
    metadata:
      labels:
        app: riot-api
    spec:
      containers:
      - name: riot-api
        image: nickpillsbury/riot-fastapi:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: riot-env-secret
---
apiVersion: v1
kind: Service
metadata:
  name: riot-api-service
spec:
  selector:
    app: riot-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer