apiVersion: v1
kind: Service
metadata:
  name: cilium-metrics
  namespace: kube-system
  labels:
    k8s-app: cilium
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: metrics
  selector:
    k8s-app: cilium
  type: ClusterIP
