apiVersion: v1
kind: Service
metadata:
  name: cilium-agent-metrics
  namespace: kube-system
  labels:
    app: cilium
spec:
  ports:
  - port: 9190
    targetPort: 9090
    protocol: TCP
  selector:
    k8s-app: cilium
