apiVersion: v1
kind: Service
metadata:
  name: iperf3-service
  namespace: network-cilium-performance-test
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8030"
spec:
  selector:
    app: iperf3-exporter
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030
  type: ClusterIP
