apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-app
  namespace: team-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team-a
  template:
    metadata:
      labels:
        app: team-a
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: team-a-service
  namespace: team-a
spec:
  selector:
    app: team-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
